<Project>
  <PropertyGroup>
    <AssemblyName>CKAN-CLI</AssemblyName>
    <OutputPath>..\_build\out\$(AssemblyName)\$(Configuration)\bin\</OutputPath>
    <BaseIntermediateOutputPath>..\_build\out\$(AssemblyName)\$(Configuration)\obj\</BaseIntermediateOutputPath>
  </PropertyGroup>
  <Import Project="Sdk.props" Sdk="Microsoft.NET.Sdk" />
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <RootNamespace>CKAN.CLI</RootNamespace>
    <TargetFramework>net8.0</TargetFramework>
    <LangVersion>12</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <PublishSingleFile>true</PublishSingleFile>
    <SelfContained>false</SelfContained>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <ErrorOnDuplicatePublishOutputFiles>false</ErrorOnDuplicatePublishOutputFiles>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <NoWarn>NU1701;CS1591;IL3000;NU1902</NoWarn>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
    <PackageReference Include="log4net" Version="2.0.15" />
  </ItemGroup>
  <ItemGroup>
    <Compile Include="..\_build\meta\GlobalAssemblyVersionInfo.cs">
      <Link>Properties\GlobalAssemblyVersionInfo.cs</Link>
    </Compile>
    <Compile Include="..\GlobalAssemblyInfo.cs">
      <Link>Properties\GlobalAssemblyInfo.cs</Link>
    </Compile>
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Core\CKAN-core.csproj">
      <SetTargetFramework>TargetFramework=net8.0</SetTargetFramework>
    </ProjectReference>
  </ItemGroup>
  <Import Project="Sdk.targets" Sdk="Microsoft.NET.Sdk" />
</Project>
